### ISSUE TITLE
Template File processing borked? Or User error

### ISSUE THREAD

**Issue by jpooler** [reverseskate/sparkleformation-workshops#5]
I'm trying to run the lab and hitting a weird error, wondering if I'm missing something obvious? I did run bundle install before trying to run this and bundle exec sfn list shows my currently created CFN stacks.

 ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

~/path/to/repo/sparkleformation-workshops] (master)$ bundle exec sfn create training-vpc --file sparkleformation/vpc.rb

ERROR: SparkleFormation::Error::NotFound::Template: Failed to locate item named: `/path/to/repo/Tools/sparkleformation/vpc.rb`

[18:24:57] user@HOST:[~/path/to/repo/sparkleformation-workshops](master)$ tree -L 3
.
├── Gemfile
├── Gemfile.lock
├── README.md
└── sparkleformation
    ├── components
    │   ├── base.rb
    │   └── vpc.rb
    ├── dynamics
    │   └── subnet.rb
    ├── example.rb
    ├── registry
    │   ├── get_azs.rb
    │   ├── github_ssh_user.rb
    │   ├── init_and_signal_user_data.rb
    │   └── nginx_hello_world.rb
    └── vpc.rb

4 directories, 12 files

With --debug on:

/usr/local/lib/ruby/gems/2.3.0/gems/sparkle_formation-3.0.10/lib/sparkle_formation/sparkle_collection.rb:183:in `get'
/usr/local/lib/ruby/gems/2.3.0/gems/sfn-3.0.18/lib/sfn/command_module/template.rb:481:in`set_paths_and_discover_file!'
/usr/local/lib/ruby/gems/2.3.0/gems/sfn-3.0.18/lib/sfn/command_module/template.rb:157:in `load_template_file'
/usr/local/lib/ruby/gems/2.3.0/gems/sfn-3.0.18/lib/sfn/command/create.rb:24:in`execute!'
/usr/local/lib/ruby/gems/2.3.0/gems/sfn-3.0.18/bin/sfn:52:in `block (4 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:26:in`block in bogo_cli_run'
/usr/local/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in`parse!'
/usr/local/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:54:in`parse'
/usr/local/lib/ruby/gems/2.3.0/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:48:in `define'
/usr/local/lib/ruby/gems/2.3.0/gems/sfn-3.0.18/bin/sfn:14:in`<top (required)>'
/usr/local/bin/sfn:23:in `load'
/usr/local/bin/sfn:23:in`<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in`kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in`exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in`invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in`start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in`block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in`<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in`<main>'

**Comment by luckymike** [comment]
This issue only occurs with 3.x versions of sparkle_formation/sfn. I'm guessing it's not a bug in those libraries, but something that needs to be updated here. I'm having trouble tracking it down though. 

For now, I'm pinning things in the Gemfile to 2.x versions.

**Comment by luckymike** [comment]
Adding `provider :aws` to the `.sfn` credentials block resolved this, so I _think_ it's an upstream bug loading the default provider.

I'll update things here :)

**Comment by jpooler** [comment]
Thanks Mike, I ended up getting it to work by using the examples from stack_master, which did include the aws provider.

**Comment by luckymike** [comment]
Great! Thanks for raising the issue.
